import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver
driver =webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in")
driver.implicitly_wait(5)
driver.execute_script("window.scrollBy(0,800);")
time.sleep(5)
book_clk = driver.find_element_by_css_selector("[title='Selenium Ruby']").click()
time.sleep(3)
reviews = driver.find_element_by_css_selector('[href="#tab-reviews"]').click()
time.sleep(3)
driver.execute_script("window.scrollBy(0,500);")
time.sleep(3)
stars_5 = driver.find_element_by_css_selector("[class='star-5']").click()
time.sleep(3)
driver.execute_script("window.scrollBy(0,800);")
comment = driver.find_element_by_id("comment")
comment.send_keys("Nice-nice book")
time.sleep(3)
Name = driver.find_element_by_id("author")
Name.send_keys("Vasya")
time.sleep(3)
email = driver.find_element_by_id("email")
email.send_keys("Vasya2011@mail.ru")
time.sleep(3)
Submit.clk = driver.find_element_by_css_selector("[name='submit']").click()
time.sleep(2)
driver.quit()