import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
driver =webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in")
driver.implicitly_wait(5)
shop = driver.find_element_by_xpath("//ul[@id='main-nav']//li[1]//a").click()
driver.execute_script("window.scrollBy(0,400);")
basket_html = driver.find_element_by_css_selector("[data-product_id='182']").click()
time.sleep(2)
basket = driver.find_element_by_css_selector("[class='wpmenucart-contents']").click()
time.sleep(2)
proceed_checkout = WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.CSS_SELECTOR,"[class='checkout-button button alt wc-forward']")))
proceed_checkout.click()
first_name = WebDriverWait(driver,5).until(EC.visibility_of_element_located((By.CSS_SELECTOR,"[name='billing_first_name']")))
first_name.send_keys("Alexey")
last_name = driver.find_element_by_css_selector("[name='billing_last_name']")
last_name.send_keys("Ivanov")
email = driver.find_element_by_css_selector("[name='billing_email']")
email.send_keys("Al_Ivanov@mail.ru")
phone = driver.find_element_by_css_selector("[name='billing_phone']")
phone.send_keys("+79877777801")
driver.execute_script("window.scrollBy(0,300);")
country = driver.find_element_by_css_selector("[id='s2id_billing_country']").click()
time.sleep(2)
select_country = driver.find_element_by_css_selector("[class='select2-input select2-focused']")
select_country.send_keys("Russia")
time.sleep(2)
choise_country = driver.find_element_by_css_selector("[class='select2-match']").click()
time.sleep(2)
street = driver.find_element_by_id("billing_address_1")
street.send_keys("Nevsky Prospekt")
town = driver.find_element_by_id("billing_city")
town.send_keys("Saint Petersburg")
state = driver.find_element_by_id("billing_state")
state.send_keys("Saint Petersburg")
postcode = driver.find_element_by_id("billing_postcode")
postcode.send_keys("190000")
time.sleep(2)
driver.execute_script("window.scrollBy(0,900);")
time.sleep(2)
payments = driver.find_element_by_css_selector("[id='payment_method_cheque']").click()
time.sleep(2)
place_order = driver.find_element_by_id("place_order").click()
time.sleep(2)
thank_you = WebDriverWait(driver,10).until(EC.text_to_be_present_in_element((By.CSS_SELECTOR,"[class='woocommerce-thankyou-order-received']"),"Thank you. Your order has been received."))
if thank_you is not None:
    print ("Надпись Thank you. Your order has been received. отображается")
else:
    print("Надписи нет")
check_payments =WebDriverWait(driver,10).until(EC.text_to_be_present_in_element((By.CSS_SELECTOR,"[class='method']>strong"),"Check Payments"))
if check_payments is not None:
    print("Статус заказа -Check Payments")
else:
    print("Другой статус")

driver.quit()